In [1]:
#Importing dependencies
import pandas as pd

In [7]:
#reading the CSV into a file
filename = "books_uniq_weeks.csv"
bestseller_df = pd.read_csv(filename,encoding = "ISO-8859-1")
bestseller_df.head()

,publisher,dagger,book_review_link,author,primary_isbn10,price,primary_isbn13,sunday_review_link,date,first_chapter_link,contributor,title,age_group,weeks_on_list
0,Riverhead,0,https://www.nytimes.com/2015/01/05/books/the-g...,Paula Hawkins,1594634025,0,9.78159E+12,https://www.nytimes.com/2015/02/01/books/revie...,2/19/17,NaN,by Paula Hawkins,THE GIRL ON THE TRAIN,NaN,102
1,Scribner,0,NaN,Anthony Doerr,1501173219,0,9.7815E+12,https://www.nytimes.com/2014/05/11/books/revie...,5/7/17,NaN,by Anthony Doerr,ALL THE LIGHT WE CANNOT SEE,NaN,81
2,Vintage,0,NaN,E L James,525431888,0,9.78053E+12,NaN,3/5/17,NaN,by E. L. James,FIFTY SHADES DARKER,NaN,66
3,St. Martin's,0,NaN,Kristin Hannah,1466850604,0,9.78147E+12,NaN,10/29/17,NaN,by Kristin Hannah,THE NIGHTINGALE,NaN,63
4,Penguin Group,0,https://www.nytimes.com/2009/02/19/books/19mas...,Kathryn Stockett,1440697663,0,9.78144E+12,NaN,4/8/12,NaN,by Kathryn Stockett,THE HELP,NaN,58

In [10]:
#creating a clean df with primary_isbn10, title, author, publisher, weeks_on_list

bestsellerclean = bestseller_df[["primary_isbn10", "title", "author", "publisher", "weeks_on_list"]]
bestsellerclean.to_csv("bestsellerbooksclean.csv")